
name: deploy

on:
  workflow_call:
    inputs:
      AZURE_CREDENTIALS:
        description: "credenciais azure"
        required: true
      IMAGE: 
        description: "nome da imagem"
        required: true
      ACR: 
        description: "Registry"
        required: true  


runs:
  using: "composite"
  steps:
    - name: Logando no Azure para Deployment
      uses: azure/login@v1
      with:
        creds: ${{ inputs.AZURE_CREDENTIALS }}

    - name: Azure WebApp
      uses: Azure/webapps-deploy@v2
      with:
        # Name of the Azure Web App
        app-name: convert-app
        images: "${{ inputs.ACR }}/${{ inputs.IMAGE }}:lastest" 
