
name: deploy

inputs:
  AZURE_CREDENTIALS:
    description: "credenciais azure"
    required: true
  IMAGE: 
    description: "nome da imagem"
    required: true
  ACR: 
    description: "Registry"
    required: true
  TAG:
    description: "tag"
    required: true


runs:
  using: "composite"
  steps:
    - name: Set the tag
      shell: bash
      run: |
        if [ -z "${{inputs.TAG}}" ]
        then
          echo "final_tag=latest" >> $GITHUB_ENV
        else
          echo "final_tag=${{inputs.TAG}}" >> $GITHUB_ENV
        fi 

    - name: Azure WebApp
      uses: Azure/webapps-deploy@v2
      with:
        # Name of the Azure Web App
        app-name: convert-app
        publish-profile: ${{ inputs.AZURE_CREDENTIALS }}
        images: "${{ inputs.ACR }}/${{ inputs.IMAGE }}:${{env.final_tag}}" 
