name: Deploy
inputs:
  token:
    description: "static site token"
  env:
    description: "environment"
runs:
  using: "composite"
  steps:
    - run: npm i -g @azure/static-web-apps-cli
      shell: bash
  
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.0
      with:
        name: build${{ inputs.env }}
        path: ./

    - name: Decompress
      uses: TonyBogdanov/zip@1.0
      with:
          args: unzip -qq ./build${{ inputs.env }}.zip -d ./

    - run: swa deploy ./build --env ${{ inputs.env }} --deployment-token ${{ inputs.token }}
      shell: bash